/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';
import {
  MatchResults,
} from '@stencil/router';


export namespace Components {

  interface AnmerkungsFeld {
    'test': string;
  }
  interface AnmerkungsFeldAttributes extends StencilHTMLAttributes {
    'test'?: string;
  }

  interface AppHome {}
  interface AppHomeAttributes extends StencilHTMLAttributes {}

  interface AppProfile {
    'match': MatchResults;
  }
  interface AppProfileAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
  }

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface FooterLeonie {}
  interface FooterLeonieAttributes extends StencilHTMLAttributes {}

  interface HeaderLeonie {}
  interface HeaderLeonieAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AnmerkungsFeld': Components.AnmerkungsFeld;
    'AppHome': Components.AppHome;
    'AppProfile': Components.AppProfile;
    'AppRoot': Components.AppRoot;
    'FooterLeonie': Components.FooterLeonie;
    'HeaderLeonie': Components.HeaderLeonie;
  }

  interface StencilIntrinsicElements {
    'anmerkungs-feld': Components.AnmerkungsFeldAttributes;
    'app-home': Components.AppHomeAttributes;
    'app-profile': Components.AppProfileAttributes;
    'app-root': Components.AppRootAttributes;
    'footer-leonie': Components.FooterLeonieAttributes;
    'header-leonie': Components.HeaderLeonieAttributes;
  }


  interface HTMLAnmerkungsFeldElement extends Components.AnmerkungsFeld, HTMLStencilElement {}
  var HTMLAnmerkungsFeldElement: {
    prototype: HTMLAnmerkungsFeldElement;
    new (): HTMLAnmerkungsFeldElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLFooterLeonieElement extends Components.FooterLeonie, HTMLStencilElement {}
  var HTMLFooterLeonieElement: {
    prototype: HTMLFooterLeonieElement;
    new (): HTMLFooterLeonieElement;
  };

  interface HTMLHeaderLeonieElement extends Components.HeaderLeonie, HTMLStencilElement {}
  var HTMLHeaderLeonieElement: {
    prototype: HTMLHeaderLeonieElement;
    new (): HTMLHeaderLeonieElement;
  };

  interface HTMLElementTagNameMap {
    'anmerkungs-feld': HTMLAnmerkungsFeldElement
    'app-home': HTMLAppHomeElement
    'app-profile': HTMLAppProfileElement
    'app-root': HTMLAppRootElement
    'footer-leonie': HTMLFooterLeonieElement
    'header-leonie': HTMLHeaderLeonieElement
  }

  interface ElementTagNameMap {
    'anmerkungs-feld': HTMLAnmerkungsFeldElement;
    'app-home': HTMLAppHomeElement;
    'app-profile': HTMLAppProfileElement;
    'app-root': HTMLAppRootElement;
    'footer-leonie': HTMLFooterLeonieElement;
    'header-leonie': HTMLHeaderLeonieElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
